name: Automatic Deployment Workflow
on:
  push:
    paths:
      - Assets/**
      - Packages/**
      - ProjectSettings/**
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deployment
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: WebGL
          allowDirtyBuild: true
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/WebGL/WebGL
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@main